### ISSUE TITLE
Automated Security Testing

### ISSUE THREAD

**Issue by heathermoses** [all-rit/ALL#129]
Description:
Find free automated security testing tools that will be usable to test the prod branch live site.

Source:
- https://snyk.io/website-scanner/ - provides documentation for each vulnerability for greater clarification
- https://hostedscan.com/scans

**Comment by Stormkiller-01** [comment]
https://docs.google.com/document/d/1cf_QfJZIrdBq2T4Y-UxH91ZkhkSnf0fwBcpDGcUiu8A/edit
