### ISSUE TITLE
Simulation Exercise

### ISSUE THREAD

**Issue by notjoncruz** [all-rit/ALL#142]
# Story: 
As a participant (user), I want to start the simulation exercise so that I can strengthen my understanding of the core aspects of autonomous systems.

# Acceptance Criteria:
- [x] A continue button in the exercise page, when clicked on, renders the simulation
- [x] A start button, when clicked on, starts the autonomous system simulation
- [x] Should not require any user input or interaction after clicking the start button

## File View:
- [x] Given when a round starts, then the access status of the round should be displayed so that I can see if the autonomous system changed the access when a threat is in the system
- [x] Given when a round starts, then the file’s sensitivity level should be displayed so that I can see if the autonomous system accurately changed the file access
- [x] Given when a round starts, then the file’s content should be displayed so that I can see if the autonomous system accurately changed the file access

## Threat Level Display:
- [x] Given when a round starts, then the threat level fed into the system should be displayed so that I can evaluate the accuracy of the autonomous system’s decisions 

### Round Counter:
- [x] Given when a round starts, then the number of the current round should be displayed so that I can view the current state of the simulation

## Score Tally:
- [x] Given when a round is in progress, then the total score count should be displayed so that I can view how many points have been lost/earned at a given point
- [x] Given when a round is in progress, then the number of correctly protected files, the number of incorrectly accessed files, and the number of incorrectly accessed files should be displayed so that I can evaluate how accurate my autonomous system’s decisions are
- [x] Given when a round is complete and the AI make a correct evaluation / decision on all files, then the system should grant the user bonus points

## Score Report:
- [x] Given when the simulation has finished, a report of the simulation should be displayed so that I can evaluate the autonomous system’s overall decision making
- [x] Final Total Score
- [x] Number of files that were correctly protected
- [x] Number of files that were incorrectly accessed
- [x] Number of files that were incorrectly restricted

**Comment by notjoncruz** [comment]
Cleaned the reducer file. In doing so, I got stuck in a bug that took me a while to figure out.

<img width="592" alt="Screenshot 2023-01-25 at 8 44 09 PM" src="https://user-images.githubusercontent.com/70080228/214737710-32ce961f-e5b5-4f8a-9f32-06f511b866e0.png">

All ten rounds can now run successfully, with a functional tally system that assigns points based on the AI's decision. 

Something to keep in mind:
- If we are utilizing the utility equation (U = S / T, where S is the sensitivity of the file, and T is the threat level) to mock the AI's decision, then an intrusion will never occur. For example, if the threat level is three, files with sensitivity levels of 4 and 5 will always be locked because 5 / 3 >= 1 and 4 / 3 >= 1. I may have interpreted the document incorrectly but I would like to seek clarification on this. This can be easily updated.

**Comment by Mster115** [comment]
> Cleaned the reducer file. In doing so, I got stuck in a bug that took me a while to figure out.
> 
> <img alt="Screenshot 2023-01-25 at 8 44 09 PM" width="592" src="https://user-images.githubusercontent.com/70080228/214737710-32ce961f-e5b5-4f8a-9f32-06f511b866e0.png">
> 
> All ten rounds can now run successfully, with a functional tally system that assigns points based on the AI's decision.
> 
> Something to keep in mind:
> 
> * If we are utilizing the utility equation (U = S / T, where S is the sensitivity of the file, and T is the threat level) to mock the AI's decision, then an intrusion will never occur. For example, if the threat level is three, files with sensitivity levels of 4 and 5 will always be locked because 5 / 3 >= 1 and 4 / 3 >= 1. I may have interpreted the document incorrectly but I would like to seek clarification on this. This can be easily updated.

@notcruz at first glance it seems you are correct, I'm not too familiar with this equation. If off hand you know of a better way to do this while allowing the user to make a simple change then explore it. If not let me know we can look into understanding this or look into clarification.
