### ISSUE TITLE
Fix Imagine activities so they are reachable from a URL

### ISSUE THREAD

**Issue by heathermoses** [all-rit/ALL#145]
# Description

Currently, going to one of the Imagine activities directly from a URL does not work as expected. The URLs lead to the home pages for the activities, but trying to advance to the next page (Avatar selection) leads to a blank screen. We need to fix this so that we can see and interact with the entire activity.

- [x] Fix Avatar selection page rendering issue
- [x] Fix Tic Tac Toe page rendering issue

# Potential fix

It seems like some imports were commented out to prevent the lab from being usable. We should try to un-comment these imports to test if the lab is usable.

In the image below, the React library is commented out, so we should try to un-comment it out.

![Image](https://user-images.githubusercontent.com/54957497/214149045-11325f64-caed-4c4e-a712-2681b3ce42a0.png)

# Links

1. Imagine activity 1: https://all.rit.edu/Imagine1
2. Imagine activity 2: https://all.rit.edu/Imagine2
3. Imagine activity 3: https://all.rit.edu/Imagine3

**Comment by Stormkiller-01** [comment]
For the tic tac toe page, is was that "react.useState()" needed to be "React.useState()". The avatar selection page rendered for me. Also, for Bias.jsx (for Imagine2 and Imagine3), needed proper useState notation "const [TimerDone, setTimerDone]" (was missing TimerDone). Then uncommented the commented code at the bottom of the file and the page after the match lobby began to work.

**Comment by Stormkiller-01** [comment]
Changed camel case typo
