### ISSUE TITLE
Defect: Lab 2 Completion Bug

### ISSUE THREAD

**Issue by Mster115** [all-rit/ALL#154]
# Defect: 
After fully completing the exercise for lab 2, there seems to be a bug that changes all text on the site to be black.

# Acceptance Criteria:
- [ ] Text color should not be effected after lab completion
- [ ] Everything else works and runs the same

The steps to replicate are  here as follows 

1. enter the exercise and play each round of the game
2. change the CSS in the update 
3. go through the colorblind section 
4. go through the remainder of the lab
5. the text on the homepage and in the window should all go to black

**Comment by jjm8759** [comment]
I am having trouble recreating this bug, are there any steps missing?

**Comment by Mster115** [comment]
> I am having trouble recreating this bug, are there any steps missing?

I cant either. im gonna close as non reproducable

**Comment by Mster115** [comment]
Can't reproduce.
