### ISSUE TITLE
Defect: Sitemap links are not working as intended

### ISSUE THREAD

**Issue by Mster115** [all-rit/ALL#155]
# Defect: 
When on the site map the Home link on the navbar adds a '#labs' to the url, this should not be added
The links for labs, goals, and contact should redirect and add these extensions ie. '#labs'

# Acceptance Criteria:
- [x] Sitemap labs goes to '#labs'
- [x] Sitemap labs goes to '#goals'
- [x] Sitemap labs goes to '#contact'
- [x] Normal navigation should be unaffected
- [x] Everything else should be unaffected
- [x] Move Home to left of Sitemap

# Context & More Info
Here is a link to a video that demonstrates the issue: https://drive.google.com/file/d/1D2n9mLtwjrt5m9U8c03nnr0PoPZZf70I/view?usp=sharing

In words: clicking the home button in the navbar from the Sitemap page will add the #labs anchor. Clicking the home button in the navbar from any of the labs will add the #goals anchor. In both of these situations, you will still be taken to the main part of the landing page; but, if you refresh the page, you'll be taken to whatever part of the page corresponds with the added anchor.

**Comment by AryanBakliwal** [comment]
Hi! I want to work on this issue, please assign me to this.
