### ISSUE TITLE
Defect: Font size changes not persistent for the main page body

### ISSUE THREAD

**Issue by Mster115** [all-rit/ALL#158]
reformatted #35 
# Defect
@suthitthazin 
> When the text size is changed, the change does not persist to other pages, specifically in the main bodies of the pages (the text in the header and the footer does change). steps to reproduce bug:
> 
> 1. Inspect element on the main text body in one of the lab pages, take note of the font size.
> 2. Click on either 'Text+' or 'Text-' button.
> 3. Take note of the font size again, you'll see it has changed.
> 4. Navigate to another page (another page in the same lab will be easier to compare).
> 5. Inspect element again and you'll notice the font size is still the initial size and not the changed size.

# Acceptance Criteria
- [ ] Font size changes are persistent
- [ ] Everything works as intended

**Comment by Mster115** [comment]
@suthitthazin 
> ![image](https://user-images.githubusercontent.com/51053679/114132759-f53e7f80-98d2-11eb-9a0d-d51a5b925a96.png) 
> this is not working correctly as intended (in editPage.js)

**Comment by dm9965** [comment]
Correction would likely be completed in a broader overall footer component/website update. Will continue development with @notcruz at a later date.

**Comment by notjoncruz** [comment]
To add onto @dm9965 , one reason that the text doesn't update is that it relies on the footer to be rendered. During an exercise, the footer is hidden, so a render doesn't occur. In the reading component, the text is fetched from the server, so the updating of the text occurs during the fetch when the text hasn't been rendered/loaded.

We can repair the issue, but it would require a good amount of modification. I believe it would be better if we wait until a new design is proposed for those tools (+, -, color change). I have an idea for this, so I think we should wait until then.

**Comment by Mster115** [comment]
@dm9965 @notcruz sounds good im going to close this issue for now

thanks for looking into it
