### ISSUE TITLE
Defect: Navbar Styling

### ISSUE THREAD

**Issue by Mster115** [all-rit/ALL#164]
# Defect: 
The google login isn’t centered vertically with the navlinks.
- [link to visual](https://docs.google.com/document/d/1xqmF8n_TbpINdVtAdyq0oVRt2cSMXjp-xufmucaNGyc/edit?disco=AAAAobaysfk)

After clicking on the ALL logo (or home navlink) to go from a lab page to the homepage, the labs navlink is highlighted, rather than goals, and the navbar background opacity is 100% instead partially transparent. Scrolling causes both properties to snap back to what they should be. The transparency issue happens on mobile too.

# Acceptance Criteria:
- [x] Google login is centered
- [x] Clicking logo displays goals navlink
- [x] Navbar set to solid
- [x] Everything else should be unaffected

**Comment by dm9965** [comment]
Removed Transparency and set logo anchor to goals section of the home page.
