### ISSUE TITLE
Defect: Overall fix of typos and grammar 

### ISSUE THREAD

**Issue by Mster115** [all-rit/ALL#168]
# Defect
- [Link](https://docs.google.com/document/d/1xqmF8n_TbpINdVtAdyq0oVRt2cSMXjp-xufmucaNGyc/edit?disco=AAAAoFtnzqw) to @2nPlusOne  's document, throughout it there are suggestions and edits that should be made
- [Resource to help make changes](https://docs.google.com/document/d/1ehqs8PeVJeq5w8Tx4698_WdJyOGw2dG7bMVt127RvDc/edit)
- Take a final look through for any more

- NOTE: Reach out to @Mster115 on how to handle and move forward with this defect

# Acceptance Criteria
- [ ] All suggestions should be addressed
- [ ] A re-proofread of everything
- [ ] Nothing else on the site should be affected

**Comment by heathermoses** [comment]
![Image](https://user-images.githubusercontent.com/54957497/219099861-9ef0b7b3-9685-4dcc-9759-24299b8de93c.png)

The "previous" button that is reused for every lab has a colon to the right. This should be removed.

**Comment by Mster115** [comment]
> ![Image](https://user-images.githubusercontent.com/54957497/219099861-9ef0b7b3-9685-4dcc-9759-24299b8de93c.png)
> 
> The "previous" button that is reused for every lab has a colon to the right. This should be removed.

@heathermoses Think I removed this in dev not sure
