### ISSUE TITLE
Defect: Lab 5 Statistic

### ISSUE THREAD

**Issue by Mster115** [all-rit/ALL#184]
# Defect

<img width="626" alt="Screenshot 2023-01-28 at 1 28 59 PM" src="https://user-images.githubusercontent.com/69928357/215284729-374d84a2-b9d1-467c-b9d8-519ce8402b7e.png">

> What is the source for this data point (which types of disabilities does it include)? According to the [NIH](https://www.nimh.nih.gov/health/statistics/attention-deficit-hyperactivity-disorder-adhd) he prevalence of adult ADHD alone is 4.4% for adults in the US.
On top of this, according to [Yale](https://www.dyslexia.yale.edu/dyslexia/dyslexia-faq/), 20% of the US population (1 in 5 people) suffer from dyslexia.
If the statistic listed does not include either of these, that would bring the datapoint closer to 30%, not including children with ADHD (roughly 2.6% of total US population).

# Steps
- [x] Statistics research completed and sources identified
- [x] Rewritten statistic in reading section
- [x] Updated pie chart
- [x] Submitted changes to testing database
- [x] Changes reviewed by Heather
- [x] Changes submitted to live database

# Acceptance Criteria
- [x] Statistic is updated
- [x] Everything else works as intended

**Comment by 2nPlusOne** [comment]
SOURCES:

According to the CDC, ~11% of U.S. adults have a cognition disability with serious difficulty concentrating, remembering, or making decisions.
https://www.cdc.gov/ncbddd/disabilityandhealth/infographic-disability-impacts-all.html
How this statistic was gathered: https://www.cdc.gov/ncbddd/disabilityandhealth/dhds/data-guide/status-and-types.html

According to the NIH, the overall prevalence of current adult ADHD is 4.4%.
https://www.nimh.nih.gov/health/statistics/attention-deficit-hyperactivity-disorder-adhd

According to NIH research, the prevalence of dyslexia is 20% in the US.
https://pubmed.ncbi.nlm.nih.gov/33278155/
