### ISSUE TITLE
Create Pie Chart in reading section

### ISSUE THREAD

**Issue by Stormkiller-01** [all-rit/ALL#243]
# Description

Now that we have a working skeleton for Lab 8, we should fill in reading section fully. Add a pi chart that has to deal with machine learning.

# Acceptance Criteria

- [x] Have statistics taken from credible resources
- [x] Make sure when its added to datagrip everything else renders successfully

**Comment by Stormkiller-01** [comment]
https://docs.google.com/document/d/1-9SOVWuRQK6nu709mwYyKqMptJntrEgnLwtGYAU0QA4/edit

**Comment by heathermoses** [comment]
The pie chart looks great, the color scheme looks great and is accessible and the data is great. Good job!
