### ISSUE TITLE
font size changes not persistent for the main page body 

### ISSUE THREAD

**Issue by suthitthazin** [all-rit/ALL#35]
When the text size is changed, the change does not persist to other pages, specifically in the main bodies of the pages (the text in the header and the footer does change).
steps to reproduce bug: 
1. Inspect element on the main text body in one of the lab pages, take note of the font size.
2. Click on either 'Text+' or 'Text-' button.
3. Take note of the font size again, you'll see it has changed.
4. Navigate to another page (another page in the same lab will be easier to compare).
5. Inspect element again and you'll notice the font size is still the initial size and not the changed size.

**Comment by st5626** [comment]
![image](https://user-images.githubusercontent.com/51053679/114132759-f53e7f80-98d2-11eb-9a0d-d51a5b925a96.png)
this is not working correctly as intended (in editPage.js)

**Comment by Mster115** [comment]
recreated
