### ISSUE TITLE
Story: Create Components for Universal Code Block

### ISSUE THREAD

**Issue by dm9965** [all-rit/ALL#423]
# Create Components for Universal Code Block

As a **developer**, I want **universal codebock components**, so that **repair code block development can be simplified**.

Associated Epic: https://github.com/all-rit/ALL/issues/422

## Definition of Done

- [x] Acceptance criteria defined
- [x] Solution tasks specified
- [x] Feature branch created
- [x] ~~Unit tests written (on API code only for now)~~
- [x] ~~Solution passes full suite of unit tests~~
- [x] Design documents updated if needed
- [x] Pull request created
- [x] Code is reviewed
- [x] Code is merged to `develop` branch
- [x] ~~Tests pass on CI~~
- [x] ~~Deployed to staging environment~~
- [x] Acceptance criteria is met

## Acceptance Criteria

- [x] Given **I want to create a JSON object in the code block**, when **I implement the <JSON/> object**, then **EXPORT CONST {props.jsonName} { } will appear and will be contained in same colored text, and will allow the user to pass text props into the component**

## Solution Tasks

- [x] Allow the function to accept props for both the json name and json elements
- [x] Component can be implemented multiple times in the same code block

**Comment by AndreasLc1103** [comment]
# This story blocks

- [ ]  #430 
- [ ]  #431
- [ ]  #432 
- [ ]  #439
