### ISSUE TITLE
Defect: Lab 6 Reading

### ISSUE THREAD

**Issue by heathermoses** [all-rit/ALL#548]
# Description

The additional links at the end of the Lab 6 Reading section ([Using AI as a Weapon?](https://www.nytimes.com/2019/06/13/us/aclu-surveillance-artificial-intelligence.html)) and ([More](https://www.nytimes.com/2020/01/18/technology/clearview-privacy-facial-recognition.html?searchResultPosition=1)) are blocked by paywalls. We need to find resources that are free and don't require you to create an account.

**Comment by Sky-De** [comment]
@heathermoses Hey, I'm interested in the project, but I'm not sure what the issue is. Can you clarify?
