### ISSUE TITLE
Story: Create Graduation Application Form Component

### ISSUE THREAD

**Issue by heathermoses** [all-rit/ALL#562]
# Create Graduation Application Form Component

As a **developer**, I want **a form component**, so that **when interacting with the lab I can store user information for the graduation information**.

Associated Epic: #490 

## Definition of Done

- [ ] Acceptance criteria defined
- [ ] Solution tasks specified
- [ ] Feature branch created
- [ ] ~~Unit tests written (on API code only for now)~~
- [ ] ~~Solution passes full suite of unit tests~~
- [ ] Design documents updated if needed
- [ ] Pull request created
- [ ] Code is reviewed
- [ ] Code is merged to `develop` branch
- [ ] ~~Tests pass on CI~~
- [ ] ~~Deployed to staging environment~~
- [ ] Acceptance criteria is met

## Acceptance Criteria

- [ ] Given **user**, when **they enter and submit their info to the form**, then **then the user state is persisted in a lab level context**
- [ ] Given **user input**, when **a user submits their responses**, then **there should be string sanitation and validation to make sure that we are protecting against any injection or cross site scripting issues**

## Solution Tasks

- [ ] Create form and style it using tailwind
- [ ] Add and handle the react context and reducers,

**Comment by AndreasLc1103** [comment]
https://tailwindcss.com/

**Comment by AndreasLc1103** [comment]
https://react.dev/learn/scaling-up-with-reducer-and-context

**Comment by AndreasLc1103** [comment]
![Image](https://github.com/all-rit/ALL/assets/16628631/12cab84d-549d-44cf-9305-3ab29a10319e)
