### ISSUE TITLE
Home button leads to different sections of home page

### ISSUE THREAD

**Issue by heathermoses** [all-rit/ALL#60]
Here is a link to a video that demonstrates the issue: [https://drive.google.com/file/d/1D2n9mLtwjrt5m9U8c03nnr0PoPZZf70I/view?usp=sharing](https://drive.google.com/file/d/1D2n9mLtwjrt5m9U8c03nnr0PoPZZf70I/view?usp=sharing)

In words: clicking the home button in the navbar from the Sitemap page will add the #labs anchor. Clicking the home button in the navbar from any of the labs will add the #goals anchor. In both of these situations, you will still be taken to the main part of the landing page; but, if you refresh the page, you'll be taken to whatever part of the page corresponds with the added anchor.

**Comment by Mster115** [comment]
recreated
