### ISSUE TITLE
Create New Labs Page

### ISSUE THREAD

**Issue by dm9965** [all-rit/ALL#652]
# Create New Labs Page

## Work to Be Completed
- [x] Create new Route from <Labs/> page in App.js
- [x] Implement new _**Explore Our Labs**_ header for the Labs Page
- [x] Create Labs Section that displays labs - Can use search bar to search lab name/type, and filter options
- [x] Create _**View Your Progress**_ section that links to user's account - If user is not logged in, direct them to log in modal that is used in the header, else send them to the profile page
- [x] Create/Reuse the **_Interested in Getting Involved?_** section from the home page

<img width="605" alt="Screenshot 2024-10-23 at 10 24 43 AM" src="https://github.com/user-attachments/assets/907c4643-0976-44e6-a4a8-60adcc2e82eb">
<img width="600" alt="Screenshot 2024-10-23 at 10 25 06 AM" src="https://github.com/user-attachments/assets/62944082-cb13-4ac3-8130-dd248d0191ad">

**Comment by mpb8984** [comment]
As of 10/31 - just needs stock photos, footer, and to fix bug with lab cards. Otherwise complete :D
