### ISSUE TITLE
Lab 2 Completion bug

### ISSUE THREAD

**Issue by AndreasLc1103** [all-rit/ALL#78]
After fully completing the exercise for lab 2, there seems to be a bug that changes all text on the site to be black.

The steps to replicate are  here as follows 

1. enter the exercise and play each round of the game
2. change the CSS in the update 
3. go through the colorblind section 
4. go through the remainder of the lab
5. the text on the homepage and in the window should all go to black

**Comment by Mster115** [comment]
recreated
